package com.nokia.ciq.validator.validator;

import com.nokia.ciq.reader.model.CiqIndex;
import com.nokia.ciq.reader.model.CiqRow;
import com.nokia.ciq.validator.config.ColumnRule;
import com.nokia.ciq.validator.model.ValidationError;

import java.util.List;

/**
 * Strategy interface for a single cell-level validation rule.
 *
 * <p>Validators are applied in order by {@link com.nokia.ciq.validator.CiqValidationEngine}.
 * Each validator is responsible for checking one aspect of a {@link ColumnRule}
 * and returning any errors found.
 *
 * <p>To add a new rule type:
 * <ol>
 *   <li>Implement this interface in a new class.</li>
 *   <li>Register it in {@code CiqValidationEngine} (in order).</li>
 * </ol>
 */
public interface CellValidator {

    /**
     * Validate a single cell value against the supplied rule.
     *
     * @param row     the current data row (used for row number and conditional lookups)
     * @param colName the column being validated
     * @param value   the raw cell value (may be null or blank)
     * @param rule    the column rule from the YAML rules file
     * @param index   the CIQ index (used for cross-reference lookups)
     * @return list of {@link ValidationError}s — empty means the cell passes this rule
     */
    List<ValidationError> validate(CiqRow row, String colName, String value,
                                   ColumnRule rule, CiqIndex index);

    /**
     * When {@code true}, the engine stops running further validators for this cell
     * as soon as this validator produces at least one error.
     *
     * <p>Used by {@link RequiredValidator}: a blank required field should not also
     * trigger allowedValues, pattern, or integer errors.
     */
    default boolean isGatekeeper() {
        return false;
    }

    /**
     * Returns the custom message if set, otherwise returns the default.
     *
     * @param msgs       the {@link com.nokia.ciq.validator.config.ColumnMessages} from the rule (may be null)
     * @param field      the constraint name (e.g. "required", "minLength", "type")
     * @param defaultMsg the fall-back message generated by the validator
     * @return custom message when configured, otherwise {@code defaultMsg}
     */
    static String msg(com.nokia.ciq.validator.config.ColumnMessages msgs, String field, String defaultMsg) {
        if (msgs == null) return defaultMsg;
        String custom;
        switch (field) {
            case "required":  custom = msgs.getRequired();  break;
            case "minLength": custom = msgs.getMinLength(); break;
            case "maxLength": custom = msgs.getMaxLength(); break;
            case "pattern":   custom = msgs.getPattern();   break;
            case "min":       custom = msgs.getMin();       break;
            case "max":       custom = msgs.getMax();       break;
            case "format":    custom = msgs.getFormat();    break;
            case "precision": custom = msgs.getPrecision(); break;
            case "type":      custom = msgs.getType();      break;
            default:          custom = null;
        }
        return custom != null ? custom : defaultMsg;
    }
}
